### PR TITLE
Insert snippet

### PR DESCRIPTION
**Pull request by kc9jud**
Hi,

I liked this extension, but I wanted a way to insert at the current cursor position rather than directly modifying a file on disk. I made some changes, as well as added an option for formatting the bibkey more nicely.

I can split this into smaller commits if you'd like.

Cheers,
Patrick

### CODE REVIEW

**Comment by zccajgb** [comment]
Hi Patrick,

This looks brilliant, I am delighted to know that this extension is useful to someone else!

Would you be able to update the change log and the README to explain your changes. Also, feel free to add yourself as a collaborator in the package.json. Happy to approve otherwise.

I'm away from my laptop this weekend but can publish the new version on Monday.

Cheers,
Joe

**Comment by kc9jud** [comment]
@zccajgb I've just added some more documentation. Let me know if you think it needs to be expanded. Thanks!

**Comment by kc9jud** [comment]
@zccajgb I fixed a few typos, hence the force pushes... I think it should be good to go now.

**Comment by zccajgb** [comment]
I've now published the update, sorry for the delay

Joe

**Pull request merged**
